on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ford
        run: |
          pip install ford

      - name: Generate Documentation
        run: |
          ford doc/ford/ford-project-file.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/ford/ford_output