on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ford
        run: |
          pip install ford

      - name: Generate Documentation
        run: |
          ford doc/ford/ford-project-file.md

      - name: Deploy Documentation
        if: github.ref == 'refs/heads/master'
        uses: HORSES3D/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages 
          folder: ./doc/ford/ford_output